" ~/.vim/sessions/TweetComplete.vim:
" Vim session script.
" Created by session.vim 2.4.7 on 25 July 2013 at 10:46:57.
" Open this file in Vim and run :source % to restore your session.

set guioptions=aegimrLtT
silent! set guifont=Monospace\ 11
if exists('g:syntax_on') != 1 | syntax on | endif
if exists('g:did_load_filetypes') != 1 | filetype on | endif
if exists('g:did_load_ftplugin') != 1 | filetype plugin on | endif
if exists('g:did_indent_on') != 1 | filetype indent on | endif
if &background != 'dark'
	set background=dark
endif
if !exists('g:colors_name') || g:colors_name != 'hybrid' | colorscheme hybrid | endif
call setqflist([])
let SessionLoad = 1
if &cp | set nocp | endif
let s:so_save = &so | let s:siso_save = &siso | set so=0 siso=0
let v:this_session=expand("<sfile>:p")
silent only
cd ~/working/software/TweetComplete
if expand('%') == '' && !&modified && line('$') <= 1 && getline(1) == ''
  let s:wipebuf = bufnr('%')
endif
set shortmess=aoO
badd +14 build.xml
badd +272 src/org/tweetcomplete/TweetComplete.java
badd +1 src/org/tweetcomplete/test/AllFastTests.java
badd +82 src/org/tweetcomplete/visitor/GenerateSQLTweetVisitor.java
badd +14 .classpath
badd +218 src/org/tweetcomplete/test/visitor/TestTweetVisitors.java
badd +2 data/tweets/tweets.csv
badd +22 sql/TweetComplete-CreateAndDelete.sql
badd +221 src/org/tweetcomplete/tweet/Tweet.java
badd +36 src/org/tweetcomplete/database/DatabaseInteractor.java
badd +68 src/org/tweetcomplete/database/sqlite/SQLiteDatabaseInteractor.java
badd +37 src/org/tweetcomplete/test/csv/TestTweetCSVFileParser.java
badd +14 sql/TweetComplete-Select.sql
badd +1 Result
badd +10 sql/TweetComplete-InsertSamples.sql
badd +166 src/org/tweetcomplete/util/Convert.java
badd +169 src/org/tweetcomplete/database/tweet/TweetCompleteDatabaseInteractionOriginator.java
badd +41 src/org/tweetcomplete/parameters/TweetCompleteParameters.java
badd +765 src/org/tweetcomplete/test/database/TestDatabaseInteractions.java
badd +1 src/org/tweetcomplete/test/AllDatabaseTests.java
badd +51 src/org/tweetcomplete/csv/TweetCSVFileParser.java
badd +19 src/org/tweetcomplete/test/util/TestConvert.java
badd +43 src/org/tweetcomplete/test/AllTests.java
badd +45 src/org/tweetcomplete/util/ExportDatabaseToXml.java
badd +50 src/org/tweetcomplete/parameters/TweetCompleteExportParameters.java
badd +12 bin/log4j.properties
badd +38 src/org/tweetcomplete/test/parameters/TestTweetCompleteParameters.java
badd +1 testing/tweetcomplete-testing-full.xml
badd +132 src/org/tweetcomplete/parameters/TweetCompleteMainParameters.java
badd +1 run/TweetComplete
badd +4 .project
badd +38 src/org/tweetcomplete/twitter/TwitterAuthorizer.java
badd +41 src/org/tweetcomplete/test/twitter/TestTwitterAuthorization.java
badd +43 src/org/tweetcomplete/twitter/TwitterAuthorization.java
badd +88 src/org/tweetcomplete/twitter/TwitterInteraction.java
badd +27 src/org/tweetcomplete/test/twitter/TestTwitterInteraction.java
badd +1 src/org/tweetcomplete/twitter/TwitterConfiguration.java
silent! argdel *
edit src/org/tweetcomplete/TweetComplete.java
set splitbelow splitright
set nosplitbelow
set nosplitright
wincmd t
set winheight=1 winwidth=1
" argglobal
setlocal fdm=manual
setlocal fde=0
setlocal fmr={{{,}}}
setlocal fdi=#
setlocal fdl=0
setlocal fml=1
setlocal fdn=20
setlocal fen
silent! normal! zE
let s:l = 36 - ((35 * winheight(0) + 19) / 38)
if s:l < 1 | let s:l = 1 | endif
exe s:l
normal! zt
36
normal! 01l
lcd ~/working/software/TweetComplete
tabnext 1
if exists('s:wipebuf')
"   silent exe 'bwipe ' . s:wipebuf
endif
" unlet! s:wipebuf
set winheight=1 winwidth=20 shortmess=filnxtToO
let s:sx = expand("<sfile>:p:r")."x.vim"
if file_readable(s:sx)
  exe "source " . fnameescape(s:sx)
endif
let &so = s:so_save | let &siso = s:siso_save

" Support for special windows like quick-fix and plug-in windows.
" Everything down here is generated by vim-session (not supported
" by :mksession out of the box).

tabnext 1
1wincmd w
if exists('s:wipebuf')
  if empty(bufname(s:wipebuf))
if !getbufvar(s:wipebuf, '&modified')
  let s:wipebuflines = getbufline(s:wipebuf, 1, '$')
  if len(s:wipebuflines) <= 1 && empty(get(s:wipebuflines, 0, ''))
    silent execute 'bwipeout' s:wipebuf
  endif
endif
  endif
endif
doautoall SessionLoadPost
unlet SessionLoad
" vim: ft=vim ro nowrap smc=128
